name: Java Spring Boot CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb
        options: >-
          --health-cmd="pg_isready -U testuser -d testdb"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: gradle

      - name: Check PostgreSQL Connection and Schema
        run: |
          sudo apt-get update && sudo apt-get install -y postgresql-client
          export PGPASSWORD=testpass
          for i in {1..20}; do
            psql -h localhost -U testuser -d testdb -c '\dt' && echo "Postgres ready" && break
            echo "Postgres not ready yet..."
            sleep 5
          done

      - name: Build Backend
        working-directory: backend
        run: ./gradlew clean build -Dspring.profiles.active=test

      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Frontend Dependencies
        working-directory: frontend
        run: npm ci

      - name: Start xvfb
        run: |
          export DISPLAY=:99
          nohup Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &

      - name: Run Frontend Tests
        working-directory: frontend
        run: npm test --watch=false --browsers=ChromeHeadless

      - name: Build Angular App
        working-directory: frontend
        run: npm run build --prod